import os
import sys
import logging
import pandas as pd

logging.basicConfig(level=logging.INFO)

def show_top5_for_country(country_code):
    """
    Simply reads the stored top-5 CSV (generated by model.py) and prints it.
    No inference or model loading is done here.
    """
    top5_file = f"data/{country_code}_top5.csv"
    if not os.path.exists(top5_file):
        logging.warning(f"[{country_code}] No top-5 file found: {top5_file}. "
                        "Please run model.py first to generate it.")
        return

    df = pd.read_csv(top5_file)
    if df.empty:
        logging.info(f"[{country_code}] {top5_file} is empty. No predictions found.")
        return

    # Optionally, sort by SHIFT or SHIFT + probability
    # SHIFT=1,7,14 are in 'shift' column
    shifts = sorted(df['shift'].unique())

    print(f"\n[{country_code}] Top-5 predictions from file '{top5_file}':\n")
    for s in shifts:
        sub = df[df['shift'] == s].copy()
        if sub.empty:
            continue
        # Sort descending by prob
        sub = sub.sort_values(by='prob', ascending=False)
        print(f"SHIFT={s}  => {len(sub)} articles")
        for i, row in sub.iterrows():
            date_str = str(row['date'])[:10]
            print(f"  - {row['title']} [Date={date_str}, Prob={row['prob']:.4f}] URL={row['url']}")
        print()

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(
        description="Show top-5 SHIFT=1/7/14 predictions from file (no re-inference)."
    )
    parser.add_argument('--country', type=str, required=True,
                        help='2-letter country code (e.g. US, JA).')
    args = parser.parse_args()

    show_top5_for_country(args.country)
